image: gitpod/workspace-base

tasks:
  - name: Setup Workspace
    command: |
      # Go
      cd $HOME
      curl -sSL https://git.io/g-install | sh -s -- bash -y

      # Vala and Lua
      sudo apt update; sudo apt upgrade -y
      sudo add-apt-repository -y ppa:vala-team/ppa
      sudo apt update; sudo apt upgrade -y
      sudo apt install -y valac lua5.1 apt-transport-https gnupg ca-certificates libvala-0.48-dev libgee-0.8-dev libjson-glib-dev libjsonrpc-glib-1.0-dev python3-pip

      # Vala language server
      sudo pip3 install -U meson ninja
      wget -c https://github.com/Prince781/vala-language-server/releases/download/0.48.4/vala-language-server-0.48.4.tar.xz
      tar -xf vala-language-server-0.48.4.tar.xz
      cd vala-language-server-0.48.4
      meson B -Dtests=false -Dman_pages=disabled
      ninja -C B
      sudo ninja -C B install
      cd ..
      rm -rf vala-language-server-0.48.4/ vala-language-server-0.48.4.tar.xz

      # D
      sudo wget https://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
      sudo apt update --allow-insecure-repositories -y
      sudo apt upgrade -y
      sudo apt -y --allow-unauthenticated install --reinstall d-apt-keyring
      sudo apt update; sudo apt upgrade -y
      sudo apt install -y dmd-compiler dmd-tools dub

      # Dart
      sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
      sudo apt update; sudo apt upgrade -y
      sudo apt install -y dart

      # Nim
      wget -qO choosenim https://nim-lang.org/choosenim/init.sh
      chmod +x choosenim
      ./choosenim -y
      echo "export PATH=$PATH:$HOME/.nimble/bin" >> $HOME/.bashrc
      rm -rf ./choosenim

      # Ruby
      wget -qO- https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
      rbenv install 3.1.1
      gem install solargraph

      # C# (Mono)
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
      sudo apt update; sudo apt upgrade -y
      sudo apt install -y mono-complete

vscode:
  extensions:
    - sumneko.lua
    - nimsaem.nimvscode
    - prince781.vala
    - castwide.solargraph
    - golang.go
    - webfreak.code-d