image: gitpod/workspace-base

tasks:
  - name: Setup Nim
    command: |
      wget -qO $HOME/choosenim https://nim-lang.org/choosenim/init.sh
      chmod +x $HOME/choosenim
      $HOME/choosenim -y
      echo "export PATH=$PATH:$HOME/.nimble/bin" >> $HOME/.bashrc

  - name: Setup Ruby
    command: |
      wget -qO- https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
      rbenv install 3.1.1
      gem install solargraph

  - name: Setup Go
    command: |
      cd $HOME
      curl -sSL https://git.io/g-install | sh -s -- bash -y
  
  - name: Setup Vala and Lua
    command:
      sudo apt update; sudo apt upgrade -y
      sudo add-apt-repository -y ppa:vala-team/ppa
      sudo apt update; sudo apt upgrade -y
      sudo apt install -y valac lua5.1
      echo 'deb http://download.opensuse.org/repositories/home:/Prince781/xUbuntu_21.04/ /' | sudo tee /etc/apt/sources.list.d/home:Prince781.list
      curl -fsSL https://download.opensuse.org/repositories/home:Prince781/xUbuntu_21.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_Prince781.gpg > /dev/null
      sudo apt update
      sudo apt install -y vala-language-server

vscode:
  extensions:
    - sumneko.lua
    - nimsaem.nimvscode
    - prince781.vala
    - castwide.solargraph
    - golang.go